name: Maven build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 7, 8, 11, 17, 18 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package --file pom.xml

    - name: Test
      run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

    # - name: Report
    #   uses: dorny/test-reporter@v1
    #   if: always()
    #   with:
    #     name: Maven Tests
    #     path: target/surefire-reports/*.xml
    #     reporter: java-junit
    #     fail-on-error: true
